In [5]:
import pandas as pd
from bike_rental.defs.assets import constants

In [12]:
bike_rental_data = pd.read_csv(constants.F_BIKE_RENTALS)
bike_rental_data.head()

   id             datetime  user_id  location_id
0   1  2011-01-01 00:05:09      158           16
1   2  2011-01-01 00:05:21      262           18
2   3  2011-01-01 00:05:39       68           18
3   4  2011-01-01 00:12:05       12            9
4   5  2011-01-01 00:25:58       91           11

In [13]:
bike_rental_data.tail()

              id             datetime  user_id  location_id
2672657  2672658  2012-12-31 23:53:45      140            1
2672658  2672659  2012-12-31 23:54:01      191           17
2672659  2672660  2012-12-31 23:55:03      283            5
2672660  2672661  2012-12-31 23:55:41      137           16
2672661  2672662  2012-12-31 23:55:53      105           17

In [14]:
bike_rental_data.shape

(2672662, 4)

In [15]:
bike_rental_data.describe()

                 id       user_id   location_id
count  2.672662e+06  2.672662e+06  2.672662e+06
mean   1.336332e+06  1.500238e+02  9.994752e+00
std    7.715312e+05  8.690642e+01  6.056529e+00
min    1.000000e+00  0.000000e+00  0.000000e+00
25%    6.681662e+05  7.500000e+01  5.000000e+00
50%    1.336332e+06  1.500000e+02  1.000000e+01
75%    2.004497e+06  2.250000e+02  1.500000e+01
max    2.672662e+06  3.000000e+02  2.000000e+01

In [17]:
bike_rental_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 2672662 entries, 0 to 2672661
Data columns (total 4 columns):
 #   Column       Dtype
---  ------       -----
 0   id           int64
 1   datetime     str
 2   user_id      int64
 3   location_id  int64
dtypes: int64(3), str(1)
memory usage: 81.6 MB

In [18]:
bike_rental_data.isna().sum()

id             0
datetime       0
user_id        0
location_id    0
dtype: int64